function ScancoParameterStressFractureCallus(handles)

try
    setStatus(handles, 'Busy');


    %%bw is meant to be a mask covering only the cortical bone in the scan
    %%bw2 is a mask representing the callus volume that is generated by
    %%morpologically operating on a thresholded value after removing bw from
    %%img
    
    %%calculates:
    %%TV of callus
    %%BV of callus
    %%callus ratio
    %%TMD of cortical bone
    %%TV of cortical bone spanning callus
    %%MV of cortical bone spanning callus
    
    [~, bw, img] = CropImg(handles.bwContour, handles.img);

    
    %Find cortical bone volume
    bw = imdilate(bw,strel('disk',3)); % Dilates the mask
    
    corticalBV = nnz(bw) * handles.info.SliceThickness^3;
    %find cortical medullary volume
    bwFilled = false(size(bw));
    [~, ~, c] = size(bw);
    for i = 1:c
        bwFilled(:,:,i) = imfill(bw(:,:,i),'holes');
    end
    bwMedullaryArea = bwFilled - bw; % Identify holes in the dilated mask
    corticalMedullaryVolume = nnz(bwMedullaryArea) * handles.info.SliceThickness^3; % Calculate volume of holes
    
    %Find estimated endosteal bone formation
    imgEndosteal = img;
    imgEndosteal(~(bwFilled-bw)) = 0; % Isolates the parts of the image with holes
    bwInterior = imgEndosteal > handles.lowerThreshold; % Removes area below threshold, leaving edge of hole
    bwInteriorWhole = imclose(bwInterior,strel('Disk',5,0));
    [callusInteriorBV, callusInteriorTV, callusInteriorBVTV] = BoneVolume(bwInterior, bwInteriorWhole, handles.info.SliceThickness);
    clear imgEndosteal;

    imgInterior = img;
    imgInterior(~imclose(bwInterior,strel('Disk',5,0))) = 0; % Leaves only the interior after close
    callusInteriorDensity = calculateDensityFromDICOM(handles.info,imgInterior);
    callusInteriorvBMD = mean(callusInteriorDensity(imclose(bwInterior,strel('Disk',5,0)))); % Gets average desnsity of interior
    clear imgInterior;
    
    imgCortical = img;
    imgCortical(~bw) = 0; % Leaves only area inside mask
    corticalDensity = calculateDensityFromDICOM(handles.info,imgCortical);
    corticalTMD = mean(corticalDensity(bw));
    clear imgCortical;
    
    imgCallus = img;
    imgCallus(bwFilled) = 0; % Leaves only area outside mask/holes
    bw2 = imgCallus > handles.lowerThreshold; % Identify area above threshold
    bw2Whole = imopen(imclose(imclose(bw2,strel('disk',15,0)),true(5,5,5)),true(3,3,3)); % TODO-test this 
    bw2Whole(bwFilled) = 0; % Leaves area outside mask/holes
    [callusBV, callusTV, callusBVTV] = BoneVolume(bw2, bw2Whole, handles.info.SliceThickness);
    imgCallus(~bw2Whole) = 0; % Removes image outside area
    callusDensity = calculateDensityFromDICOM(handles.info,imgCallus); % Get image density
    callusvBMD = mean(callusDensity(bw2Whole)); % Calculates average density
    clear imgCallus

    % Reorder dimensions for viewing
    bw = permute(bw,[3,2,1]);
    bw2Whole = permute(bw2Whole,[3,2,1]);
    
    % Plot shapes of bw and bwWhole
    shp = shpFromBW(bw,3);
    figure;
    plot(shp,'LineStyle','none','FaceColor','w');
    hold on;
    shp = shpFromBW(bw2Whole,3);
    plot(shp,'LineStyle','none','FaceColor','r','FaceAlpha',0.4);
    camlight();
    hold off;
    
    out = { handles.pathstr,...
        datestr(now),...
        callusTV,...
        callusBV,...
        callusBVTV,...
        callusvBMD,...
        callusInteriorTV,...
        callusInteriorBV,...
        callusInteriorBVTV,...
        callusInteriorvBMD,...
        corticalTMD,...
        corticalBV,...
        corticalMedullaryVolume,...
        handles.info.SliceThickness,...
        handles.lowerThreshold
        };
        
    outHeader = {'File Location',...
        'Date Analyzed',...
        'Callus Total Volume (mm^3)',...
        'Callus Bone Volume(mm^3)',...
        'Callus Bone Volume Fraction',...
        'Callus Volumetric Bone Mineral Density (mgHa/ccm)',...
        'Endosteal Total Volume (mm^3)',...
        'Endosteal Bone Volume (mm^3)',...
        'Endosteal Volume Fraction',...
        'Endosteal Volumetric Bone Mineral Density (mgHa/ccm)',...
        'Cortical Tissue Mineral Density (mgHa/ccm)',...
        'Cortical Volume (mm^3)',...
        'Medullary Total Volume (mm^3)',...
        'Slice Thickness (mm)',...
        'Lower Threshold'...
        };

    PrintReport(fullfile(handles.pathstr,'StressFractureCallusResults.txt'), outHeader, out);
    setStatus(handles, 'Not Busy')
catch err
    reportError(err, handles);
end